moonD4rk/HackBrowserData

- core/browser.go
- core/browser_windows.go
> Add chrome beta support for Windows

- README.md
- core/browser.go
- core/browser_windows.go
added Opera,OperaGX,Vivaldi for windows
> Added some more browsers (Windows)

- core/browser.go
- core/data/output.go
- core/data/parse.go
Added credit card info for chromium-based browsers (I don't know if the GUID is needed, but it was a simple fix for an error I was encountering)
> Credit card info

- core/browser_darwin.go
- core/browser_linux.go
- core/browser_windows.go
> update firefox path profile

- core/data/parse.go
- core/decrypt/decrypt_linux.go
I only tested in Firefox 78.7.0esr (Debian 10), but this patch might also fix #43
> fix: decrypt password in firefox

- cmd/hack-browser-data/main.go
- internal/browingdata/browsingdata.go
- internal/browingdata/creditcard/creditcard.go
- internal/browingdata/localstorage/localstorage.go
- internal/browingdata/outputter.go
- internal/browingdata/password/password.go
- internal/browser/browser.go
- internal/browser/browser_windows.go
- internal/browser/chromium/chromium.go
- internal/browser/chromium/chromium_darwin.go
- internal/browser/chromium/chromium_linux.go
- internal/browser/chromium/chromium_windows.go
- internal/browser/firefox/firefox.go
- internal/decrypter/decrypter_darwin.go
- internal/decrypter/decrypter_linux.go
- internal/utils/fileutil/filetutil.go
- internal/utils/typeutil/typeutil.go
- internal/utils/typeutil/typeutil_test.go
Reference issues
https://github.com/moonD4rk/HackBrowserData/issues/134
https://github.com/moonD4rk/HackBrowserData/issues/95
> feat: support export multiple user from browser

- internal/browingdata/browsingdata.go
fix:'The process cannot access the file because it is being used by another process' Error
Issue: #151
> fix:' cannot access the file ' Error

- README.md
- README_ZH.md
- internal/decrypter/decrypter_darwin.go
Add `release` and `lint` github status badge
> docs: update ci status badge

- internal/browser/browser.go
- internal/browser/browser_windows.go
- internal/browser/chromium/chromium.go
- internal/browser/chromium/chromium_darwin.go
- internal/decrypter/decrypter_darwin.go
- internal/decrypter/decrypter_linux.go
- internal/decrypter/decrypter_windows.go
latest version of Chrome store `Cookies` under `Network` Folder, after this PR could find right cookie database.
this could fix #158 #147 #134
> fix: find cookie file failed on windows

- internal/provider/provider.go
- internal/provider/provider_windows.go
> 增加小智双核与搜狗浏览器

- internal/provider/provider.go
- internal/provider/provider_windows.go
add sogou browser and dc browser profile path
```go
dcbrowserUserDataPath  = homeDir + "/AppData/Local/DCBrowser/User Data/Default/"
sougouUserDataPath     = homeDir + "/AppData/Roaming/SogouExplorer/Webkit/Default/"
```
> feat: add sogou and dc browser

- README.md
- README_ZH.md
- browingdata/bookmark/bookmark.go
- browingdata/browsingdata.go
- browingdata/cookie/cookie.go
- browingdata/creditcard/creditcard.go
- browingdata/download/download.go
- browingdata/extension/extension.go
- browingdata/history/history.go
- browingdata/localstorage/localstorage.go
- browingdata/password/password.go
- crypto/crypto_darwin.go
- crypto/crypto_linux.go
- crypto/crypto_windows.go
Remove duplicate code and more Go style.
> refactor: format browsing data export

- README.md
> docs: Add Contribution Guide in the readme.

- CONTRIBUTING.md
- typos.toml
> chore: remove unused config file

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/unittest.yml
- Close #303
- Upgrade GitHub Actions to v4 in all workflows
- Fix zipping and uploading of Linux arm64 assets in release workflow
- Simplify and remove unnecessary steps in build workflow
> feat: Upgrade GitHub Actions to v4 for greater stability

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/unittest.yml
- .golangci.yml
- browser/chromium/chromium.go
- Updated configuration file, add more golangci linters Close #282 
- Add Go build cache to CI, improve the running speed of Github Actions runner Close #303
> ci: Improve Golang code quality with updated lint configuration file

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/unittest.yml
- .golangci.yml
- browser/chromium/chromium.go
Use `go mod download` instead `go get`
> fix: Upgrade CI resolve the issue of cache expiration.

- browser/chromium/chromium_darwin.go
- browser/chromium/chromium_linux.go
- crypto/asn1pbe.go
- crypto/pbkdf2.go
> refactor: Refactor encryption modules for Chromium browsers.

- browser/browser.go
- browser/chromium/chromium.go
- browser/firefox/firefox.go
- Refactored variable names for clarity and consistency in multiple files
- Updated logic to filter sensitive items based on a flag
- Implemented a function to skip processing specific paths to improve performance
Ref: https://github.com/moonD4rk/HackBrowserData/issues/352
> fix: skip chromium snapshot dir to find right password database

- .github/dependabot.yml
- README.md
- README_ZH.md
- cmd/hack-browser-data/main.go
> docs: Update version to 0.4.6 and enhance documentation

- .github/dependabot.yml
> chore: Optimize GitHub actions and dependencies updates

- crypto/crypto.go
The old reference was removed/moved
> chore: updated source reference

- browser/browser_windows.go
- browser/consts.go
feat: support 360speedX browser(password\cookie\bookmark\session storage)
fix: Update the configuration file path of Sogou browser(password\cookie\bookmark\history\local storage\session storage)
> feat: support 360speedX and sogou
