moonD4rk/HackBrowserData

utils/utils.go
I was unable to extract firefox cookie data. I got this error and cookies file was empty (exactly same behavior for json format):
```
cmd.go:101: error csvutil: error calling MarshalText for type time.Time: Time.MarshalText: year outside of range [0,9999]
```
This is because some web sites have to habit to set "Expires" date of cookies on `31 Dec 9999 23:59:59 GMT`, then firefox saves them (in column "expiry" of "moz_cookies" table) as timestamp of value `253402300799`.
When cookies structure is marshalled (writeToCsv and writeToJson functions) the times are converted to the local timezone and then checked and converted to csv/json.
In my partucular case (TZ is GMT+1) one hour is added to the timestamp 253402300799 and the result is `1 Jan 10000 00:59:59 +0100 CET`.  Year 10000 is outside …
=> Fix "year outside of range" error getting cookies on Firefox

core/browser.go, core/data/output.go, core/data/parse.go
添加了读取 Chromium 内核浏览器 Download History 的功能。另外在此谢谢师傅写的工具，很好用。
csv 格式输出
json 格式输出
=> add parse Chromium download history

core/browser.go, core/data/parse.go
添加了读取 Firefox Download History 的功能。
不过有个小问题，在 Firefox 的下载记录里没找到记录 MIME 类型 的字段。
BTW 新年快乐🎉🎉🎉
csv 格式输出
json 格式输出
=> add parse Firefox download history

README_ZH.md
Optimize some translation, grammar and format.
> 优化一些翻译、语法和格式。
=> Optimize the Chinese version of README

core/decrypt/decrypt.go
An attempt to resolve #87 . 
Don't know how to reproduce the issue, so I'm not sure if this really address the issue. However, I believe that checking the length of `encryptPass` is necessary in AES decryption.
Also removed an unused variable.
=> Add ciphertext length check in AES decryption

internal/browser/browser_windows.go
- Function `getProfiles()` has been added in `browser_windows.go` to identify the path of the Chrome profiles.
- `operaGXProfilePath` changed to `/AppData/Roaming/Opera Software/Opera GX Stable/`.
- Before: 
- After:
=> Profile folder for Chrome and OperaGx fixed for windows

README.md, README_ZH.md, go.mod, go.sum, internal/browingdata/bookmark/bookmark.go, internal/browingdata/browsingdata.go, internal/browingdata/cookie/cookie.go, internal/browingdata/creditcard/creditcard.go, internal/browingdata/download/download.go, internal/browingdata/extension/extension.go, internal/browingdata/history/history.go, internal/browingdata/localstorage/localstorage.go, internal/browingdata/outputter.go, internal/browingdata/password/password.go
reference:
https://github.com/moonD4rk/HackBrowserData/issues/142
https://github.com/moonD4rk/HackBrowserData/issues/139
=> fix: filter result if item is empty and add utf8 encoder to csv file

.golangci.yml, go.mod, internal/browingdata/bookmark/bookmark.go, internal/browingdata/browsingdata.go, internal/browingdata/cookie/cookie.go, internal/browingdata/creditcard/creditcard.go, internal/browingdata/download/download.go, internal/browingdata/extension/extension.go, internal/browingdata/history/history.go, internal/browingdata/localstorage/localstorage.go, internal/browingdata/outputter.go, internal/browingdata/outputter_test.go, internal/browingdata/password/password.go, internal/browser/browser.go, internal/browser/browser_windows.go, internal/browser/chromium/chromium.go, internal/browser/chromium/chromium_darwin.go, internal/browser/chromium/chromium_linux.go, internal/browser/chromium/chromium_windows.go, internal/browser/firefox/firefox.go, internal/decrypter/decrypter.go, internal/decrypter/decrypter_darwin.go, internal/decrypter/decrypter_linux.go, internal/decrypter/decrypter_windows.go, internal/utils/fileutil/filetutil.go, internal/utils/typeutil/typeutil_test.go
add those linters
``` yml
linters:
enable:
- 'asciicheck'
- 'deadcode'
- 'depguard'
- 'dogsled'
- 'errorlint'
- 'exportloopref'
- 'gofmt'
- 'goheader'
- 'goimports'
- 'gomodguard'
- 'goprintffuncname'
- 'gosec'
- 'govet'
- 'ineffassign'
- 'makezero'
- 'misspell'
- 'paralleltest'
- 'prealloc'
- 'predeclared'
- 'revive'
- 'typecheck'
- 'unconvert'
- 'varcheck'
- 'whitespace'
```
also exclude some rulers
``` yml
issues:
exclude-use-default: false
exclude:
- should have a package comment
- should have comment
- G101
- G103
- G304
- G401
- G404
- G502
- G505
exclude-rules:
- path: internal/browser/browser\.go
linters:
- 'deadcode'
- 'varcheck'
- 'unused'
```
=> refactor: formatting code used to pass golangci-lint rules

internal/browingdata/history/history.go
If the null title is filtered out, a lot of browsing records will be missing. The COALESCE function fix this issue. At the same time, COALESCE function also helps solving the warning caused by _last_visit_date_ being null.
=> fix: issue of data missing caused by title being null

README.md, README_ZH.md, cmd/hack-browser-data/main.go
The full prompt is "password|bookmark|cookie|history|credit card|download|localStorage|extension"
Signed-off-by: yuxiaojun <yuxiaojun@uniontech.com>
=> fix: the bug that the command line Usage prompt is incomplete

go.mod, internal/log/log.go
1. Disable terminal output of colored logs
2. Fix incorrect golang caller skip level
=> fix: wrong log caller skip level

browingdata/bookmark/bookmark.go, browingdata/cookie/cookie.go, browingdata/download/download.go, browingdata/extension/extension.go, browingdata/history/history.go, browingdata/localstorage/localstorage.go, crypto/crypto.go, crypto/crypto_darwin.go, crypto/crypto_linux.go
Fix `revive` lint.
Renaming `masterKey` as `_`.
=> fix: renaming unused parameter

.golangci.yml, README.md, README_ZH.md, browingdata/bookmark/bookmark.go, browingdata/browsingdata.go, browingdata/cookie/cookie.go, browingdata/creditcard/creditcard.go, browingdata/download/download.go, browingdata/extension/extension.go, browingdata/history/history.go, browingdata/localstorage/localstorage.go, browingdata/password/password.go, browingdata/sessionstorage/sessionstorage.go, browser/browser.go, browser/browser_darwin.go, browser/browser_linux.go, browser/browser_windows.go, browser/chromium/chromium.go, browser/chromium/chromium_darwin.go, browser/chromium/chromium_linux.go, browser/chromium/chromium_windows.go, browser/consts.go, browser/firefox/firefox.go, cmd/hack-browser-data/main.go, go.mod
[Arc Browser](https://arc.net/)
```
Arc: 113.0.5672.126 (Official Build) (arm64) 
OS: macOS ****
JavaScript: V8 11.3.244.11
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Command Line: /Applications/Arc.app/Contents/MacOS/Arc --flag-switches-begin --flag-switches-end
Executable Path: /Applications/Arc.app/Contents/MacOS/Arc
Profile Path: /Users/****/Library/Application Support/Arc/User Data/Default
Linker: lld
```
Close #212
=> feat: support Arc browser for macOS

browser/browser.go, browser/firefox/firefox.go, cmd/hack-browser-data/main.go
- fix panic in case browser data error
- ignore files walk error in firefox, since it will be returned if at least one invocation of file walk function returns error
- use `WalkDir` instead of `Walk` since its faster
- simplify logic a bit in firefox browser init
=> fix: Bug fixes in firefox file walk

browser/chromium/chromium_windows.go
解密重装系统前的数据失败时，增加报错信息。
---
我本来是想重构一下，让 Master Key 解密失败时也能导出无需解密的数据，不过重构到一半看到你在 24c90f5b92a356631c5ea14ecff1f05eac7903dd ([feat/library](https://github.com/moonD4rk/HackBrowserData/commits/feat/library)) 也有重构计划，所以就不弄了，我改到一半的结果在 e6230418341a6de7d44233768f8afdf127ed09d1 ([分支](https://github.com/stevenlele/HackBrowserData/tree/refactor))，修改点如下：
- 目前 Browser 的 Chromium/Firefox 多态没什么意义，本来 pickXxx 就是分开的，各个数据项也是分开解析的，所以重构去掉了
- 把临时文件复制移动到各个数据 parsing 里面，这样就不会留下临时数据；部分没必要复制的就不再复制了
- 把 Yandex 逻辑合并到 Chromium 里面，减少重复代码
- 重构不是很彻底，比如可以弄一个 BrowserType 的枚举写进 Browser 里面（看到你弄了），这样更稳健
代码就留着供参考，如果你觉得哪些做法不合适可以指正讨论一下，或者直接无视就好。
=> fix: warn if failed to decrypt master key

browser/chromium/chromium.go, browsingdata/extension/extension.go, item/filename.go, utils/fileutil/filetutil.go
Chromium 目前是扫描 Extensions 目录，导致结果有多版本重复、获取到的名称和描述是语言文件的 key、缺少自行加载的扩展等问题，因此改成直接读取 Secure Preferences（旧版本为 Preferences）文件，Profile 路径通过临时文件传递（最好是重构之后直接在程序内传递）。
Firefox 的 defaultLocale 一般是英文，因此添加了一个语言匹配的逻辑，目标语言放在 `var lang = language.Und` 全局变量处，不过没有添加命令行参数，可以之后添加，类似 `--lang zh-CN`，然后这样解析即可：
```go
import "golang.org/x/text/language"
tag, _ := language.Parse(langStr)
```
`err` 可以忽略，因为可能已经解析出部分 `tag`，解析不出来也只是默认的 `Und`。
=> feat: improve extension parsing

browsingdata/outputter.go
Remove space in json output.
Before
```json
[
{
"Name": "name1",
"Password": "password1",
"Infos": [
{
"Infos1": "Infos1",
"Infos2": "Infos2",
"Infos3": 1
}
]
},
{
"Name": "name2",
"Password": "password2",
"Infos": [
{
"Infos1": "Infos1",
"Infos2": "",
"Infos3": 1
}
]
}
]
```
After:
```json
[
{
"Name": "name1",
"Password": "password1",
"Infos": [
{
"Infos1": "Infos1",
"Infos2": "Infos2",
"Infos3": 1
}
]
},
{
"Name": "name2",
"Password": "password2",
"Infos": [
{
"Infos1": "Infos1",
"Infos2": "",
"Infos3": 1
}
]
}
]
```
=> refactor: optimize JSON indent output format

browser/chromium/chromium.go, browsingdata/browsingdata.go
Fix the bug that causes the program to unexpectedly exit when unable to open a file for copying. 
This error mainly occurs when the database file is being used by another process, especially in the case of files storing cookies. 
Currently, only skipping the error is possible; other methods are required for a complete fix.
Close
- https://github.com/moonD4rk/HackBrowserData/issues/255
- https://github.com/moonD4rk/HackBrowserData/issues/233
- https://github.com/moonD4rk/HackBrowserData/issues/222
Ref
- https://github.com/moonD4rk/HackBrowserData/issues/243
=> fix: Improve error handling in browsing data and file copying functions

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/unittest.yml, .gitignore, item/item.go, item/item_test.go
- Add GitHub actions for unit testing, linting, building, and releasing
- Use a matrix strategy to test on different versions and platforms
- Update setup-go and go-version options for compatibility
- Format code and build zip files for different operating systems
- Upload releases to GitHub with specific asset names and types
=> ci: Optimize GitHub actions and update Go versions.

.github/workflows/build.yml, .github/workflows/contributors.yml, .github/workflows/lint.yml
- Update Github Actions workflows to use `main` branch instead of `master`.
- Rename `master` branch to `main` in `lint.yml` and `build.yml` files.
- Change default branch to `main` in `contributors.yml` workflow file.
- Close #270
=> ci: Update default branch references in GitHub Actions workflows

.github/workflows/lint.yml, .github/workflows/unittest.yml, .gitignore, browsingdata/localstorage/localstorage.go, browsingdata/sessionstorage/sessionstorage.go, crypto/crypto_windows.go, logger/logger.go, typos.toml
=> chore: add typos check linter in github actions

browser/firefox/firefox.go, browser/firefox/firefox_test.go, browsingdata/password/password.go, crypto/crypto.go, go.mod, go.sum
Process masterkey when init firefox instance
```golang
// GetMasterKey returns master key of Firefox. from key4.db
func (f *Firefox) GetMasterKey() ([]byte, error) {
tempFilename := item.FirefoxKey4.TempFilename()
// Open and defer close of the database.
keyDB, err := sql.Open("sqlite", tempFilename)
if err != nil {
return nil, fmt.Errorf("open key4.db error: %w", err)
}
defer os.Remove(tempFilename)
defer keyDB.Close()
globalSalt, metaBytes, err := queryMetaData(keyDB)
if err != nil {
return nil, fmt.Errorf("query metadata error: %w", err)
}
nssA11, nssA102, err := queryNssPrivate(keyDB)
if err != nil {
return nil, fmt.Errorf("query NSS private error: %w", err)
}
return processMasterKey(globalSalt, metaBytes, nssA11, nssA102)
}
```
=> feat: refactor firefox get master key retrieval and decryption functions.

.typos.toml, browser/chromium/chromium_windows.go, browser/firefox/firefox.go, browsingdata/cookie/cookie.go, browsingdata/creditcard/creditcard.go, browsingdata/password/password.go, crypto/asn1pbe.go, crypto/asn1pbe_test.go, crypto/crypto.go, crypto/crypto_darwin.go, crypto/crypto_linux.go, crypto/crypto_test.go, crypto/crypto_windows.go
=> feat: Refactor crypto decryption functions for consistency and error handling

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/unittest.yml, .typos.toml, CONTRIBUTING.md, browser/chromium/chromium_windows.go, browser/firefox/firefox.go, browser/firefox/firefox_test.go, browsingdata/cookie/cookie.go, browsingdata/creditcard/creditcard.go, browsingdata/password/password.go, crypto/asn1pbe.go, crypto/asn1pbe_test.go, crypto/crypto.go, crypto/crypto_darwin.go, crypto/crypto_linux.go, crypto/crypto_test.go, crypto/crypto_windows.go, go.mod, go.sum, typos.toml
Optimized the logic for obtaining Firefox keys and added more unit tests for encryption and decryption.
Ref Issuse:
- https://github.com/moonD4rk/HackBrowserData/issues/297
- https://github.com/moonD4rk/HackBrowserData/issues/301
- https://github.com/moonD4rk/HackBrowserData/issues/303
Ref PR:
- https://github.com/moonD4rk/HackBrowserData/pull/300
- https://github.com/moonD4rk/HackBrowserData/pull/302
- https://github.com/moonD4rk/HackBrowserData/pull/304
=> dev: Optimize encryption and decryption module

.github/workflows/build.yml
setup-go@v4 actions enabled cache falg by default. This conflicts with actions/cache. 
```yaml
- name: Set up Go ${{ matrix.goVer }}
uses: actions/setup-go@v5
with:
go-version: ${{ matrix.goVer }}
cache: false
id: go
- name: cache go modules
uses: actions/cache@v4
with:
path: |
~/go/pkg/mod
~/.cache/go-build
key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
restore-keys: |
${{ runner.os }}-go-
```
=> ci: Disable build setup-go, solve multiple cache conflicts.

browser/chromium/chromium.go, browser/firefox/firefox.go
- Implement error handling for path permission errors in `chromiumWalkFunc`
- Refactor `firefoxWalkFunc` to handle permission errors and log warnings
- Add import statement for `log/slog` in `firefox/firefox.go`
If access to the browser configuration file is not permitted, print an error log and skip.
Close https://github.com/moonD4rk/HackBrowserData/issues/345
=> fix: Improve error handling if walk browser profile dir

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml, .goreleaser.yml
- Add configuration files for `goreleaser.yml` and GitHub workflows
- Update Go version to `1.22.x`
- Adjust workflow names and triggers in `.github/workflows` folder
Close #275
=> ci: Refactor project workflows, build with goreleaser

README.md, README_ZH.md, cmd/hack-browser-data/main.go
- Add new command line flag for full export browsing data
- Refactor README files for clarity and updated information
=> docs: Update version to 0.4.6 and enhance documentation

README.md, README_ZH.md, cmd/hack-browser-data/main.go
=> docs: Update the document version to 0.4.6 

cmd/hack-browser-data/main.go, utils/fileutil/filetutil.go, utils/fileutil/fileutil_test.go
- Refactored the `CompressDir` function in the `fileutil` package for improved error handling and handling of edge cases
- Improved error messages for various file operations
- Added test file and created tests for the `CompressDir` function in the `fileutil` package
Close https://github.com/moonD4rk/HackBrowserData/issues/366
=> fix: Improve error handling and fix wrong compress dir for windows

browser/chromium/chromium.go
fix [Chromium-based browsers find wrong user](https://github.com/moonD4rk/HackBrowserData/issues/447)
=> fix: skip chromium-based browser 'def' dir

browser/chromium/chromium.go, browserdata/bookmark/bookmark.go, browserdata/browserdata.go, browserdata/cookie/cookie.go, browserdata/creditcard/creditcard.go, browserdata/download/download.go, browserdata/history/history.go, browserdata/localstorage/localstorage.go, browserdata/password/password.go, browserdata/sessionstorage/sessionstorage.go, crypto/crypto.go
=> Merge dev into main: decryption password failure and modify browserdata log level

.github/workflows/lint.yml, .golangci.yml
- Upgraded golangci-lint from v1 to v2 configuration format for better maintainability
- Updated GitHub Actions workflow from v6 to v8 with golangci-lint v2.2.0
- Established a permissive baseline configuration to unblock development
This project hasn't been updated for a while and was using an outdated golangci-lint v1 configuration that was incompatible with modern tooling. The CI/CD pipeline was failing due to configuration incompatibilities. This PR modernizes the linting infrastructure while temporarily relaxing rules to allow gradual code quality improvements.
1. **Configuration Migration**: Migrated `.golangci.yml` from v1 to v2 format
2. **GitHub Actions Update**: Updated workflow to use `golangci-lint-action@v8` with `v2.2.0`
3. **Formatter Separation**: Configured formatters …
=> fix: upgrade golangci-lint to v2 and modernize configuration
